cloudian/urls.py
from django.urls import path

from . import views

app_name = 'cloudian'

urlpatterns = [
    path('', views.main, name='main'),
    path('wc_create/', views.wc_create, name='wc_create'),
    path('<int:img_id>/', views.output, name='wc_output'),
    path('en/', views.main_en, name='main_en'),
    path('en/wc_create/', views.wc_create_en, name='wc_create_en'),
    path('en/<int:img_id>/', views.output_en, name='wc_output_en'),
    path('kr/', views.main_kr, name='main_kr'),
    path('kr/wc_create/', views.wc_create_kr, name='wc_create_kr'),
    path('kr/<int:img_id>/', views.output_kr, name='wc_output_kr'),
    path('es/', views.main_es, name='main_es'),
    path('es/wc_create/', views.wc_create_es, name='wc_create_es'),
    path('es/<int:img_id>/', views.output_es, name='wc_output_es'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cloudian.urls')),
]

cloudian/models.py
from django.db import models


class Text(models.Model):
    text = models.TextField()

cloudian/views.py
from django.shortcuts import render, redirect

from konlpy.tag import Okt
from collections import Counter
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import stylecloud
import random


def main(request):
    return redirect('cloudian:main_en')


def output(request, img_id):
    return redirect('cloudian:wc_output_en', img_id=img_id)


def wc_create(request):
    return redirect('cloudian:wc_create_en')


def main_kr(request):
    return render(request, 'cloudian/base_kr.html')


def main_en(request):
    return render(request, 'cloudian/base.html')


def main_es(request):
    return render(request, 'cloudian/base_es.html')


def output_kr(request, img_id):
    context = {'img_id': img_id}
    return render(request, 'cloudian/wordcloud_kr.html', context)


def output_en(request, img_id):
    context = {'img_id': img_id}
    return render(request, 'cloudian/wordcloud.html', context)


def output_es(request, img_id):
    context = {'img_id': img_id}
    return render(request, 'cloudian/wordcloud_es.html', context)


def wc_create_kr(request):
    wc_text = request.POST.get('content')
    wc_shape = request.POST.get('shapes')
    rannum = random.randint(1, 10000000)
    name = "cloudian_" + str(rannum) + "_kr.png"

    if " " in wc_text:
        lists = [wc_text]

        okt = Okt()
        morphs = []

        for sentence in lists:
            morphs.append(okt.pos(sentence))

        noun_adj_adv_list = []

        for sentence in morphs:
            for word, tag in sentence:
                if (tag in ['Noun']) and ("것" not in word) and ("내" not in word) and ("나" not in word) and (
                        "수" not in word) and ("게" not in word) and ("말" not in word) and ("로서" not in word):
                    noun_adj_adv_list.append(word)
                if tag in ['Adjective']:
                    noun_adj_adv_list.append(word)
                if tag in ['Adverb']:
                    noun_adj_adv_list.append(word)
                if (tag in ['Foreign']) and ("(" not in word) and (")" not in word) and ("!" not in word) and (
                        "?" not in word) and ("." not in word) and ("," not in word) and (
                        "\'" not in word) and ("\\" not in word) and ("\n" not in word) and ("\r" not in word):
                    noun_adj_adv_list.append(word)
                if (tag in ['Alpha']) and ("(" not in word) and (")" not in word) and ("!" not in word) and (
                        "?" not in word) and ("." not in word) and ("," not in word) and (
                        "\'" not in word) and ("\"" not in word):
                    noun_adj_adv_list.append(word)

        if len(noun_adj_adv_list) != 0:
            count = Counter(noun_adj_adv_list)

            words = dict(count.most_common())

            stylecloud.gen_stylecloud(text=words,
                                      icon_name=wc_shape,
                                      background_color="white",
                                      font_path="/home/cloba/cloudian/static/BMHANNAPro.ttf",
                                      output_name="/home/cloba/cloudian/static/cloudImage/" + name, )

    return redirect('cloudian:wc_output_kr', img_id=rannum)


def wc_create_en(request):
    wc_text = request.POST.get('content')
    wc_shape = request.POST.get('shapes')
    rannum = random.randint(1, 10000000)
    name = "cloudian_" + str(rannum) + ".png"

    if wc_text is not None:
        eng_stop_words = list(stopwords.words("english"))
        filtered_list = []

        lists = [wc_text]
        words_list = []

        for sentence in lists:
            words_list.append(word_tokenize(sentence))

        for sentence in words_list:
            for word in sentence:
                if (word.casefold() not in eng_stop_words) and ("(" not in word) and (")" not in word) and ("!" not in word) and (
                        "?" not in word) and ("." not in word) and ("," not in word) and ("\'" not in word) and (
                        "\"" not in word) and ("\\" not in word) and ("\n" not in word) and ("\r" not in word) and (
                        ":" not in word) and (";" not in word) and ("{" not in word) and ("}" not in word) and (
                        "[" not in word) and ("]" not in word) and ("-" not in word) and ("=" not in word):
                    filtered_list.append(word)

        if len(filtered_list) != 0:
            count = Counter(filtered_list)

            texts = dict(count.most_common())

            stylecloud.gen_stylecloud(text=texts,
                                      icon_name=wc_shape,
                                      background_color="white",
                                      font_path="/home/cloba/cloudian/static/IBMPlexSans-SemiBold.ttf",
                                      output_name="/home/cloba/cloudian/static/cloudImage/" + name, )

    return redirect('cloudian:wc_output', img_id=rannum)


def wc_create_es(request):
    wc_text = request.POST.get('content')
    wc_shape = request.POST.get('shapes')
    rannum = random.randint(1, 10000000)
    name = "cloudian_" + str(rannum) + "_es.png"

    if wc_text is not None:
        es_stop_words = list(stopwords.words("spanish"))
        filtered_list = []

        lists = [wc_text]
        words_list = []

        for sentence in lists:
            words_list.append(word_tokenize(sentence))

        for sentence in words_list:
            for word in sentence:
                if (word.casefold() not in es_stop_words) and ("(" not in word) and (")" not in word) and ("!" not in word) and (
                        "?" not in word) and ("." not in word) and ("," not in word) and ("\'" not in word) and (
                        "\"" not in word) and ("\\" not in word) and ("\n" not in word) and ("\r" not in word) and (
                        ":" not in word) and (";" not in word) and ("{" not in word) and ("}" not in word) and (
                        "[" not in word) and ("]" not in word) and ("-" not in word) and ("=" not in word):
                    filtered_list.append(word)

        if len(filtered_list) != 0:
            count = Counter(filtered_list)

            texts = dict(count.most_common())

            stylecloud.gen_stylecloud(text=texts,
                                      icon_name=wc_shape,
                                      background_color="white",
                                      font_path="/home/cloba/cloudian/static/IBMPlexSans-SemiBold.ttf",
                                      output_name="/home/cloba/cloudian/static/cloudImage/" + name, )

    return redirect('cloudian:wc_output_es', img_id=rannum)

templates/cloudian/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR&display=swap" rel="stylesheet">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- cloudian CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Cloudian</title>
</head>
<body>
    <div class="page-header">
        <h1>Word Cloud Generator</h1>
    </div>

    <div class="content container">
        <br />
        Language: <a href="{% url 'cloudian:main_kr' %}">한국어</a>
        <a href="{% url 'cloudian:main_en' %}">English</a>
        <a href="{% url 'cloudian:main_es' %}">Español</a><br />
        <br />
        <br />
        How to use:<br />
        1. Type the text you want to make into a wordcloud in the box below.<br />
        2. Choose the word cloud shape you want from 'Shapes'.<br />
        3. Press the 'Generate' button and wait.<br />
        4. Download the completed word cloud image.<br />
        <br />
        Notes:<br />
        1. Words in parentheses may not be recognized properly.<br />
        2. If the sentence is too short or the number of words is small, the word cloud may not be generated properly.<br />
        3. Some punctuation marks or numbers can be printed together.<br />
    </div>

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <div class="content container">
        <br/>
        <br/>
        <form action="{% url 'cloudian:wc_create_en' %}" method="post">
            {% csrf_token %}
            <label for="shapes">Shapes</label>
            <select id="shapes" name="shapes">
                <option value="fas fa-anchor">Anchor</option>
                <option value="fas fa-apple-alt">Apple</option>
                <option value="fas fa-bell">Bell</option>
                <option value="fas fa-bread-slice">Bread</option>
                <option value="fas fa-circle">Circle</option>
                <option value="fas fa-cloud">Cloud</option>
                <option value="fas fa-crown">Crown</option>
                <option value="fas fa-dog">Dog</option>
                <option value="fas fa-exclamation">Exclamation</option>
                <option value="fas fa-flag">Flag</option>
                <option value="fas fa-filter">Filter</option>
                <option value="fas fa-fish">Fish</option>
                <option value="fas fa-heart">Heart</option>
                <option value="fas fa-user">Human</option>
                <option value="fas fa-square">Round Square</option>
                <option value="fas fa-skull">Skull</option>
                <option value="fas fa-comment">Speech bubble</option>
                <option value="fas fa-square-full">Square</option>
                <option value="fas fa-star">Star</option>
            </select>
            <textarea style="resize:none" name="content" id="content" rows="10"></textarea>
            <input type="submit" value="Generate">
        </form>
        Example: <img src="../../static/cloudImage/cloudian_example.png", alt="Example image", width="20%", height="20%"/>
    </div>
    <br />

    <div class="content container">
        <br />
        Pohangjecheol High School AI & Math Club "Math AI" (Youtube Channel: <a href="https://www.youtube.com/c/MathMVP">Math MVP</a>)<br />
        <br />
        This site was created by Donghyeon Gu. (gdonghyeon@postech.ac.kr) <br />
        <br />
        Other wordcloud generator: <a href="https://www.wordclouds.com/">wordcloud.com</a><br />
        <br/>
        <div>
            <a href=#none id="show" onclick="if(hide.style.display=='none') {hide.style.display='';show.innerText='▲Fold'} else {hide.style.display='none';show.innerText='▶License'}">▶License</a>
            <div id="hide" style="display: none">
                Copyright (c) 2012 Andreas Christian Mueller<br />
                <br />
                Permission is hereby granted, free of charge, to any person obtaining a copy of<br />
                this software and associated documentation files (the "Software"), to deal in<br />
                the Software without restriction, including without limitation the rights to<br />
                use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of<br />
                the Software, and to permit persons to whom the Software is furnished to do so,<br />
                subject to the following conditions:<br />
                <br />
                The above copyright notice and this permission notice shall be included in all<br />
                copies or substantial portions of the Software.<br />
                <br />
                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR<br />
                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS<br />
                FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR<br />
                COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER<br />
                IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN<br />
                CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.<br />
                <br />
                <br />
                MIT License<br />
                <br />
                Copyright (c) 2019-2020 Max Woolf<br />
                <br />
                Permission is hereby granted, free of charge, to any person obtaining a copy<br />
                of this software and associated documentation files (the "Software"), to deal<br />
                in the Software without restriction, including without limitation the rights<br />
                to use, copy, modify, merge, publish, distribute, sublicense, and/or sell<br />
                copies of the Software, and to permit persons to whom the Software is<br />
                furnished to do so, subject to the following conditions:<br />
                <br />
                The above copyright notice and this permission notice shall be included in all<br />
                copies or substantial portions of the Software.<br />
                <br />
                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR<br />
                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS<br />
                FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR<br />
                COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER<br />
                IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN<br />
                CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.<br />
            </div>
        </div>
    </div>
</body>
</html>

templates/cloudian/base_es.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR&display=swap" rel="stylesheet">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- cloudian CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Cloudian</title>
</head>
<body>
    <div class="page-header">
        <h1>Generador de nubes de palabras</h1>
    </div>

    <div class="content container">
        <br />
        Language: <a href="{% url 'cloudian:main_kr' %}">한국어</a>
        <a href="{% url 'cloudian:main_en' %}">English</a>
        <a href="{% url 'cloudian:main_es' %}">Español</a><br />
        <br />
        <br />
        Cómo usar:<br />
        1. Escribe el texto que quieres hacer en una nube de palabras en la caja que está abajo.<br />
        2. Elige la forma de nube de palabra que quieras de 'Las Formas'.<br />
        3. Presiona el botón 'Generar' y espera.<br />
        4. Descarga la imagen completa de la nube de palabra.<br />
        <br />
        Notas:<br />
        1. Las palabras entre paréntesis pueden no ser reconocidas adecuadamente.<br />
        2. Si la oración es demasiado corta o el número de palabras es pequeño, la nube de palabra puede no generarse adecuadamente.<br />
        3. Algunas marcas de puntuación o números pueden ser impresos juntos.<br />
    </div>

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <div class="content container">
        <br/>
        <br/>
        <form action="{% url 'cloudian:wc_create_es' %}" method="post">
            {% csrf_token %}
            <label for="shapes">Las Formas:</label>
            <select id="shapes" name="shapes">
                <option value="fas fa-anchor">Ancla</option>
                <option value="fas fa-flag">Bandera</option>
                <option value="fas fa-bell">Campana</option>
                <option value="fas fa-circle">Círculo</option>
                <option value="fas fa-heart">Corazón</option>
                <option value="fas fa-crown">Corona</option>
                <option value="fas fa-skull">Cráneo</option>
                <option value="fas fa-square-full">Cuadrado</option>
                <option value="fas fa-square">Cuadrado redondo</option>
                <option value="fas fa-star">Estrella</option>
                <option value="fas fa-filter">Filtro</option>
                <option value="fas fa-comment">Globo de discurso</option>
                <option value="fas fa-user">Humano</option>
                <option value="fas fa-apple-alt">Manzana</option>
                <option value="fas fa-cloud">Nube</option>
                <option value="fas fa-bread-slice">Pan</option>
                <option value="fas fa-dog">Perro</option>
                <option value="fas fa-fish">Pez</option>
                <option value="fas fa-exclamation">Signo de exclamación</option>
            </select>
            <textarea style="resize:none" name="content" id="content" rows="10"></textarea>
            <input type="submit" value="Generar">
        </form>
        Exemplo: <img src="../../static/cloudImage/cloudian_example.png", alt="Exemplo", width="20%", height="20%"/>
    </div>
    <br />

    <div class="content container">
        <br />
        Pohangjecheol High School AI & Math Club "Math AI" (Youtube Channel: <a href="https://www.youtube.com/c/MathMVP">Math MVP</a>)<br />
        <br />
        This site was created by Donghyeon Gu. (gdonghyeon@postech.ac.kr) <br />
        <br />
        Otro generador de nudos de palabras: <a href="https://www.wordclouds.com/">wordcloud.com</a><br />
        <br />
        <div>
            <a href=#none id="show" onclick="if(hide.style.display=='none') {hide.style.display='';show.innerText='▲Fold'} else {hide.style.display='none';show.innerText='▶License'}">▶License</a>
            <div id="hide" style="display: none">
                Copyright (c) 2012 Andreas Christian Mueller<br />
                <br />
                Permission is hereby granted, free of charge, to any person obtaining a copy of<br />
                this software and associated documentation files (the "Software"), to deal in<br />
                the Software without restriction, including without limitation the rights to<br />
                use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of<br />
                the Software, and to permit persons to whom the Software is furnished to do so,<br />
                subject to the following conditions:<br />
                <br />
                The above copyright notice and this permission notice shall be included in all<br />
                copies or substantial portions of the Software.<br />
                <br />
                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR<br />
                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS<br />
                FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR<br />
                COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER<br />
                IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN<br />
                CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.<br />
                <br />
                <br />
                MIT License<br />
                <br />
                Copyright (c) 2019-2020 Max Woolf<br />
                <br />
                Permission is hereby granted, free of charge, to any person obtaining a copy<br />
                of this software and associated documentation files (the "Software"), to deal<br />
                in the Software without restriction, including without limitation the rights<br />
                to use, copy, modify, merge, publish, distribute, sublicense, and/or sell<br />
                copies of the Software, and to permit persons to whom the Software is<br />
                furnished to do so, subject to the following conditions:<br />
                <br />
                The above copyright notice and this permission notice shall be included in all<br />
                copies or substantial portions of the Software.<br />
                <br />
                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR<br />
                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS<br />
                FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR<br />
                COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER<br />
                IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN<br />
                CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.<br />
            </div>
        </div>
    </div>
</body>
</html>

templates/cloudian/base_kr.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR&display=swap" rel="stylesheet">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- cloudian CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Cloudian</title>
</head>
<body>
    <div class="page-header">
        <h1>단어구름 생성기</h1>
    </div>

    <div class="content container">
        <br />
        Language: <a href="{% url 'cloudian:main_kr' %}">한국어</a>
        <a href="{% url 'cloudian:main_en' %}">English</a>
        <a href="{% url 'cloudian:main_es' %}">Español</a><br />
        <br />
        <br />
        사용 방법:<br />
        1. 단어구름으로 만들고 싶은 내용을 아래에 입력한다.<br />
        2. '모양 선택'에서 원하는 단어구름 모양을 고른다.<br />
        3. '단어구름 생성' 버튼을 누르고 기다린다.<br />
        4. 완성된 단어구름 이미지를 다운로드 받는다.<br />
        <br />
        주의 사항:<br />
        1. 괄호 안에 들어 있는 단어는 제대로 인식하지 못할 수 있습니다.<br />
        2. 문장이 너무 짧거나 단어의 수가 적으면 모양이 제대로 안 나올 수 있습니다.<br />
        3. 문장부호나 숫자가 함께 출력될 수 있습니다.<br />
    </div>

    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

    <div class="content container">
        <br/>
        <br/>
        <form action="{% url 'cloudian:wc_create_kr' %}" method="post">
            {% csrf_token %}
            <label for="shapes">모양 선택:</label>
            <select id="shapes" name="shapes">
                <option value="fas fa-dog">강아지</option>
                <option value="fas fa-cloud">구름</option>
                <option value="fas fa-flag">깃발</option>
                <option value="fas fa-filter">깔때기</option>
                <option value="fas fa-exclamation">느낌표</option>
                <option value="fas fa-anchor">닻</option>
                <option value="fas fa-square">둥근 정사각형</option>
                <option value="fas fa-fish">물고기</option>
                <option value="fas fa-comment">말풍선</option>
                <option value="fas fa-star">별</option>
                <option value="fas fa-bread-slice">빵</option>
                <option value="fas fa-apple-alt">사과</option>
                <option value="fas fa-user">사람</option>
                <option value="fas fa-crown">왕관</option>
                <option value="fas fa-circle">원</option>
                <option value="fas fa-square-full">정사각형</option>
                <option value="fas fa-bell">종</option>
                <option value="fas fa-heart">하트</option>
                <option value="fas fa-skull">해골</option>
            </select>
            <textarea style="resize:none" name="content" id="content" rows="10"></textarea>
            <input type="submit" value="단어구름 생성">
        </form>
        예시: <img src="../../static/cloudImage/cloudian_example_kr.png", alt="워드클라우드 이미지 예시", width="20%", height="20%"/>
    </div>
    <br />

    <div class="content container">
        <br />
        포항제철고 인공지능 수학 동아리 Math AI (유튜브 채널: <a href="https://www.youtube.com/c/MathMVP">Math MVP</a>)<br />
        <br />
        This site was created by Donghyeon Gu. (gdonghyeon@postech.ac.kr) <br />
        <br />
        다른 워드클라우드 생성기: <a href="https://www.wordclouds.com/">wordcloud.com</a><br />
        <br />
        <div>
            <a href=#none id="show" onclick="if(hide.style.display=='none') {hide.style.display='';show.innerText='▲Fold'} else {hide.style.display='none';show.innerText='▶License'}">▶License</a>
            <div id="hide" style="display: none">
                Copyright (c) 2012 Andreas Christian Mueller<br />
                <br />
                Permission is hereby granted, free of charge, to any person obtaining a copy of<br />
                this software and associated documentation files (the "Software"), to deal in<br />
                the Software without restriction, including without limitation the rights to<br />
                use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of<br />
                the Software, and to permit persons to whom the Software is furnished to do so,<br />
                subject to the following conditions:<br />
                <br />
                The above copyright notice and this permission notice shall be included in all<br />
                copies or substantial portions of the Software.<br />
                <br />
                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR<br />
                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS<br />
                FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR<br />
                COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER<br />
                IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN<br />
                CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.<br />
                <br />
                <br />
                MIT License<br />
                <br />
                Copyright (c) 2019-2020 Max Woolf<br />
                <br />
                Permission is hereby granted, free of charge, to any person obtaining a copy<br />
                of this software and associated documentation files (the "Software"), to deal<br />
                in the Software without restriction, including without limitation the rights<br />
                to use, copy, modify, merge, publish, distribute, sublicense, and/or sell<br />
                copies of the Software, and to permit persons to whom the Software is<br />
                furnished to do so, subject to the following conditions:<br />
                <br />
                The above copyright notice and this permission notice shall be included in all<br />
                copies or substantial portions of the Software.<br />
                <br />
                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR<br />
                IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS<br />
                FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR<br />
                COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER<br />
                IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN<br />
                CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.<br />
            </div>
        </div>
    </div>
</body>
</html>